### ISSUE TITLE
Install php7 only, no need of nginx

### ISSUE THREAD

**Issue by educate** [jogolor/openshift-cartridge-php#1]
Hi,
Thank you for sharing your cartridge with us, I have a question, if I don't want to use NGINX, and I'm not gonna install nginx cartridge, then I can just ignore 
**Pass PHP scripts to PHP-FPM**
Is there anything I'm missing? Please take some time to give me a hint.

Best regards,
Ethan

**Comment by jogolor** [comment]
Apache + PHP 7 ?

**Comment by educate** [comment]
that's right, I once installed `jogolor/openshift-cartridge-php` , but found no document root.

**Comment by jogolor** [comment]
It 's a pity this cartridge is not compiled for Apache.
You can: 1)  recompile php 7 to support apache; 2) edit your Apache configuration file to enable php support.

**Comment by educate** [comment]
Thank you for your advice!
